language: python

services:
  - docker

stages:
  - test-pr
  - name: "Build&Publish"
    if: branch = master

jobs:
  include:
    - stage: test-pr
      name: "Test PR"
      if: type = pull_request
      before_script:
        - echo $dockerpass | docker login -u $dockeruser --password-stdin
      install:
        - pip install mkdocs-material
      script:
        - mkdocs build
        - docker build -t $prrepo:$TRAVIS_PULL_REQUEST .
        - docker push $prrepo:$TRAVIS_PULL_REQUEST

    - stage: "Build&Publish"
      name: "Build&Deploy" 
      if: type = push
      before_script:
        - echo $dockerpass | docker login -u $dockeruser --password-stdin
      install:
        - pip install mkdocs-material
      script:
        - mkdocs build
        - docker build -t $docsrepo:$tag .
        - docker push $docsrepo:$tag
